<?php
/**
 * @file
 * eMusik specific functionality lays in this module.
 */

/**
 * Implements hook_menu().
 */
function emusik_menu() {
  $items = array();

  $items['admin/config/emusik'] = array(
    'title' => 'eMusik',
    'description' => 'Manage eMusik.',
    'position' => 'right',
    'weight' => 20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['json/search/node/%'] = array(
    'page callback' => 'json_search_results_endpoint',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function emusik_theme($existing, $type, $theme, $path) {
  $hooks = array();

  $hooks['emusik_search_header'] = array(
    'variables' => array(
      'search_query' => '',
    ),
    'template' => 'emusik_search_header',
    'path' => $path . '/templates',
  );

  return $hooks;
}

/**
 * Implements hook_block_info().
 */
function emusik_block_info() {
  $blocks = array();

  $blocks['emusik_mkdru_node'] = array(
    'info' => t('node search menu'),
  );

  $blocks['emusik_search_header'] = array(
    'info' => t('Search header for mkdru search'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function emusik_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'emusik_search_header':
      $block['subject'] = t('Search');
      $block['content'] = emusik_search_header();
      break;
  }

  return $block;
}

/**
 * Block view content handler.
 */
function emusik_search_header() {
  return theme('emusik_search_header', array('search_query' => arg(2)));
}

/**
 * Return count of items in search result in JSON format.
 *
 * @param string $query
 *   Search query
 */
function json_search_results_endpoint($query) {
  $result = array(
    'count' => count((array) node_search_execute($query)),
  );
  drupal_json_output($result);
}
