<?php
/**
 * @file
 * eMusik specific functionality lays in this module.
 */

/**
 * Implements hook_menu().
 */
function emusik_menu() {
  $items = array();

  $items['admin/config/emusik'] = array(
    'title' => 'eMusik',
    'description' => 'Manage eMusik.',
    'position' => 'right',
    'weight' => 20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function emusik_block_info() {
  $blocks = array();

  $blocks['emusik_mkdru_node'] = array(
    'info' => t('node search menu'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function emusik_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'emusik_mkdru_node':
      $block['subject'] = t('Node search');
      $block['content'] = '213';
      break;
  }

  return $block;
}
